// <auto-generated />
using Exercice01API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice01API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercice01API.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AvatarURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatarURL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarURL = " URL1 ",
                            Email = "Jean.Dakd@gmail.com",
                            FirstName = "Jean ",
                            LastName = " Dakd",
                            Password = " ICOZJQI",
                            Phone = "07112562"
                        },
                        new
                        {
                            Id = 2,
                            AvatarURL = " URL 2",
                            Email = "Alfred.aziod@gmail.com",
                            FirstName = "Alfred ",
                            LastName = "aziod",
                            Password = " QZCNQj",
                            Phone = "0658421895"
                        },
                        new
                        {
                            Id = 3,
                            AvatarURL = " URL 3",
                            Email = "Nicolas.oczz@gmail.com",
                            FirstName = "Nicolas ",
                            LastName = "oczz",
                            Password = " KOQVN?QKkd",
                            Phone = "0715289173"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
